# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: {POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 4000:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
  
  redis-server:
    image: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6380:6379