# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: devpassword
      POSTGRES_USER: devuser
      POSTGRES_DB: customers
    ports:
      - 4000:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
  
  redis-server:
    image: redis
    environment:
      REDIS_PASSWORD: devredispassword
    ports:
      - 5000:6379